default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8
  timeout: 5000
  username: root
  password: root

development:
  <<: *default
  database: livogis_dev

production:
  <<: *default
  database: livogis_prod

test:
  <<: *default
  database: livogis_test
